### ISSUE TITLE
millisecond

### ISSUE THREAD

**Issue by jabbalaci** [SawdustSoftware/simpleflake#1]
It's really nothing but

s/milisecond_time/millisecond_time/

Great project BTW.

**Comment by malicustommade** [comment]
Fixed at 61a93b5e3a96176488d563e44acca30677b64389.

Thank you, and thanks for the mention in your article! (https://pythonadventures.wordpress.com/2013/07/06/generate-random-hash/)

**Comment by jabbalaci** [comment]
I've used SimpleFlake in a project of mine since then: https://github.com/jabbalaci/PrimCom . In the folder `data`, see the files *.json. The IDs are created with SimpleFlake. Thanks for this great project.
