### ISSUE TITLE
Blog page related to simpleflake down?

### ISSUE THREAD

**Issue by holtkamp** [SawdustSoftware/simpleflake#9]
A significant amount of hyperlinks on the interwebs point to https://www.custommade.com/simpleflake-distributed-id-generation-for-the-lazy, which seems down 😢

**Comment by makmanalp** [comment]
@holtkamp uh oh, that's a shame. I found a cached copy here: http://archive.li/VpeGP
Also for a video version check out: https://www.youtube.com/watch?v=SCQPBGi_QRk but the text is more detailed IIRC.

Hope this helps! Looking back, I'm not necessarily convinced that this is the best for all use cases, but I think for us at the time it made sense. The blog post should help you understand the tradeoffs, and it shouldn't be hard to make a version of your own that suits yours. Let me know if you have specific questions. Good luck!

**Comment by holtkamp** [comment]
@makmanalp thanks for the swift response, will have a look! Did you know about this article?

https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/

**Comment by makmanalp** [comment]
@holtkamp  Not that one specifically, but they seem to go with the UUIDv1 rearranging method, which I was also mentioning as an alternative in the other thread. Depending on your usecase, having the machine-specific stuff can be helpful or a waste of space that you might rather fill up with more precise timing or more random bits. There's a slide in the presentation for that I think.
